language: python
python:
  - "3.4"
  - "3.5"
services:
  - postgresql
# Install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database sincserver;' -U postgres
script:
  - python manage.py test
