language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - postgresql
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database sincserver;' -U postgres
  - export DATABASE_URL=postgresql://postgres@localhost/sincserver
script:
  - coverage run --source="." manage.py test
after_success:
  - coveralls
