# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170112_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrolment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseenrolments', to='courses.Course'),
        ),
    ]
