# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20161219_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Region'),
        ),
    ]
