# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 14:06
from __future__ import unicode_literals

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20170117_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(clubs.models.get_national_region), to='clubs.Region'),
        ),
    ]
