# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_qualification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_instructor_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
