# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_certificate_is_instructor_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
